CREATE TABLE TAX_PERCENT
(
	SLNO 								INTEGER UNSIGNED PRIMARY KEY,
	PERCENT							FLOAT UNSIGNED NOT NULL,
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE		DATE
);

INSERT TAX_PERCENT VALUES (1, 4, SYSDATE(), SYSDATE());
INSERT TAX_PERCENT VALUES (2, 12.5, SYSDATE(), SYSDATE());

CREATE TABLE COMPANY
(
	SLNO 								INTEGER UNSIGNED PRIMARY KEY,
	COMPANY							VARCHAR(50) UNIQUE,
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE		DATE
);

INSERT COMPANY VALUES (1, 'GURU MURUGAN & CO.', SYSDATE(), SYSDATE());
INSERT COMPANY VALUES (2, 'SUKUM CORP', SYSDATE(), SYSDATE());

CREATE TABLE PER
(
	SLNO 								INTEGER UNSIGNED PRIMARY KEY,
	PER_TYPE						VARCHAR(20) UNIQUE,
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE		DATE
);

INSERT PER VALUES (1, 'PIECE', SYSDATE(), SYSDATE());
INSERT PER VALUES (2, 'KG', SYSDATE(), SYSDATE());

CREATE TABLE SALES
(
	COMPANY 						VARCHAR(50), 
	BOOK_NUMBER 				VARCHAR(15) ,
	BILL_NUMBER					INTEGER UNSIGNED ,
	BILL_AMOUNT					FLOAT (20, 2),
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE		DATE,
	CONSTRAINT SALES_COMPANY_FK FOREIGN KEY (COMPANY) REFERENCES COMPANY (COMPANY) ON DELETE NO ACTION,
	CONSTRAINT SALES_PK PRIMARY KEY (COMPANY, BOOK_NUMBER, BILL_NUMBER)
);

CREATE TABLE SALES_ITEMS
(
	BOOK_NUMBER 				VARCHAR(15) ,
	BILL_NUMBER					INTEGER UNSIGNED,
	SLNO 								INTEGER UNSIGNED,
	TAX_PERCENT 					FLOAT UNSIGNED,
	AMOUNT							FLOAT (20, 2),
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE		DATE,
	CONSTRAINT SALES_ITEMS_BOOK_NUMBER_FK FOREIGN KEY (BOOK_NUMBER) REFERENCES SALES (BOOK_NUMBER) ON DELETE NO ACTION,
	CONSTRAINT SALES_ITEMS_BILL_NUMBER_FK FOREIGN KEY (BILL_NUMBER) REFERENCES SALES (BILL_NUMBER) ON DELETE NO ACTION,
	CONSTRAINT SALES_ITEMS_TAX_PERCENT_FK FOREIGN KEY (TAX_PERCENT) REFERENCES TAX_PERCENT (PERCENT) ON DELETE NO ACTION,
	CONSTRAINT SALES_ITEMS_PK PRIMARY KEY (BOOK_NUMBER, BILL_NUMBER, SLNO)
);

CREATE TABLE STOCK
(
	SLNO 								INTEGER UNSIGNED,
	COMPANY							VARCHAR(50),
	ITEM_ID							VARCHAR(20),
	PRIMARY_CATEGORY	    VARCHAR(30),
	SECONDARY_CATEGORY	VARCHAR(30),
	GENERAL_CATEGORY   	VARCHAR(30),
	CUSTOM_TAG_1				VARCHAR(30),
	CUSTOM_TAG_2				VARCHAR(30),
	DESCRIPTION 					VARCHAR(300),
	TAX_PERCENT					FLOAT UNSIGNED,
	COMMENTS						VARCHAR(300),
	CREATION_DATE				DATE,
	LAST_MODIFIED_DATE 	DATE,
	
	CONSTRAINT STOCK_COMPANY_FK FOREIGN KEY (COMPANY) REFERENCES COMPANY (COMPANY) ON DELETE NO ACTION,
	CONSTRAINT STOCK_TAX_PERCENT_FK FOREIGN KEY (TAX_PERCENT) REFERENCES TAX_PERCENT (PERCENT) ON DELETE NO ACTION,
	CONSTRAINT STOCK_PK PRIMARY KEY (SLNO, COMPANY, ITEM_ID)
);



CREATE TABLE BILLS
(
	COMPANY 						VARCHAR(50), 
	BOOK_NUMBER 				VARCHAR(15) ,
	BILL_NUMBER					INTEGER UNSIGNED ,
	SALES_TAX						FLOAT(20,2),
	VAT									FLOAT(20,2),
	BILL_AMOUNT					FLOAT (20, 2),
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE		DATE,
	CONSTRAINT BILLS_COMPANY_FK FOREIGN KEY (COMPANY) REFERENCES COMPANY (COMPANY) ON DELETE NO ACTION,
	CONSTRAINT BILLS_PK PRIMARY KEY (COMPANY, BOOK_NUMBER, BILL_NUMBER)
);




CREATE TABLE BILL_ITEMS
(
	BOOK_NUMBER 				VARCHAR(15) ,
	BILL_NUMBER					INTEGER UNSIGNED ,
	SLNO 								INTEGER UNSIGNED,
	ITEM_ID							VARCHAR(20),
	DESCRIPTION					VARCHAR(300),
	QUANTITY						INTEGER UNSIGNED,
	PER 									VARCHAR(15)
	PRICE 								FLOAT (20, 2),
	BILL_AMOUNT					FLOAT (20, 2),
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE		DATE,
	CONSTRAINT BILL_ITEMS_BOOK_NUMBER_FK FOREIGN KEY (BILL_NUMBER) REFERENCES BILLS (BILL_NUMBER) ON DELETE NO ACTION,
	CONSTRAINT BILL_ITEMS_PK PRIMARY KEY ( BOOK_NUMBER, BILL_NUMBER, SLNO)
);


CREATE TABLE GMC_SKC_VITHU_BILL
(
	COMPANY                         VARCHAR(5),
	BOOK_NUMBER 				VARCHAR(15) ,
	BILL_NUMBER					INTEGER UNSIGNED,
	16_I_SALES_AMOUNT     DOUBLE(10,2) UNSIGNED,
	16_I_SALES_TAX 	        DOUBLE(10,2) UNSIGNED,
	12_5_I_SALES_AMOUNT  DOUBLE(10,2) UNSIGNED,
	12_5_I_SALES_TAX	        DOUBLE(10,2) UNSIGNED,
	4_I_SALES_AMOUNT       DOUBLE(10,2) UNSIGNED,
	4_I_SALES_TAX		        DOUBLE(10,2) UNSIGNED,
	16_II_SALES_AMOUNT    DOUBLE(10,2) UNSIGNED,
	10_II_SALES_AMOUNT    DOUBLE(10,2) UNSIGNED,
	4_II_SALES_AMOUNT      DOUBLE(10,2) UNSIGNED,
	12_II_SALES_AMOUNT    DOUBLE(10,2) UNSIGNED,
	NTAS 								DOUBLE(10,2) UNSIGNED,
	TOTAL								DOUBLE(20,2) UNSIGNED,
	DATE_OF_SALES				DATE,
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE		DATE,
	CONSTRAINT VITHU_BKNO_BLNO_PK PRIMARY KEY ( COMPANY, BOOK_NUMBER, BILL_NUMBER)
);

INSERT INTO GMC_SKC_VITHU_BILL VALUES('GMC','A1',23 ,0 , 0, 0,0,0,0,0,0,0,0,123,123,SYSDATE(),SYSDATE(),SYSDATE());
INSERT INTO GMC_SKC_VITHU_BILL VALUES('GMC','A1',24,0,0,0,0,0,0,0,0,0,0,125,125,SYSDATE(),SYSDATE(),SYSDATE());


INSERT INTO GMC_SKC_VITHU_BILL VALUES('SKC','B1',23,0,0,0,0,0,0,0,0,0,0,123,123,SYSDATE(),SYSDATE(),SYSDATE());
INSERT INTO GMC_SKC_VITHU_BILL VALUES('SKC','B2',23,0,0,0,0,0,0,0,0,0,0,123,123,SYSDATE(),SYSDATE(),SYSDATE());


SELECT * FROM GMC_SKC_VITHU_BILL WHERE DATE_OF_SALES = '';

SELECT * FROM GMC_SKC_VITHU_BILL WHERE COMPANY='GMC';
SELECT * FROM GMC_SKC_VITHU_BILL WHERE COMPANY='SKC';


UPDATE GMC_SKC_VITHU_BILL SET BILL_NUMBER = 25 WHERE BILL_NUMBER = 24 AND BOOK_NUMBER = 'A1' AND COMPANY ='GMC';

DELETE FROM GMC_SKC_VITHU_BILL WHERE BILL_NUMBER = 24 AND BOOK_NUMBER = 'A1' AND COMPANY ='GMC';


UPDATED
------------------------
CREATE TABLE GMC_SKC_VITHU_BILL
(
	COMPANY                     VARCHAR(5),
	BOOK_NUMBER 				VARCHAR(10) ,
	BILL_NUMBER					INTEGER UNSIGNED,
	12_5_I_SALES_AMOUNT  		DOUBLE(10,2) UNSIGNED,
	12_5_I_SALES_TAX	        DOUBLE(10,2) UNSIGNED,
	4_I_SALES_AMOUNT       		DOUBLE(10,2) UNSIGNED,
	4_I_SALES_TAX		        DOUBLE(10,2) UNSIGNED,
	NTAS 						DOUBLE(10,2) UNSIGNED,
	TOTAL						DOUBLE(20,2) UNSIGNED,
	DATE_OF_SALES				DATE,
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE			DATE,
	CONSTRAINT VITHU_BKNO_BLNO_PK PRIMARY KEY ( COMPANY, BOOK_NUMBER, BILL_NUMBER)
);

----13 JUL 2011
//added new columns for 5% and 14.5%
ALTER TABLE `gmc`.`gmc_skc_vithu_bill` 
ADD COLUMN `14_5_I_SALES_AMOUNT` DOUBLE(10,2) ZEROFILL UNSIGNED NULL  AFTER `4_I_SALES_TAX` ,
ADD COLUMN `14_5_I_SALES_TAX` DOUBLE(10,2) UNSIGNED ZEROFILL NULL  AFTER `14_5_I_SALES_AMOUNT` , 
ADD COLUMN `5_I_SALES_AMOUNT` DOUBLE(10,2) UNSIGNED ZEROFILL NULL  AFTER `14_5_I_SALES_TAX` ;
ADD COLUMN `5_I_SALES_TAX` DOUBLE(10,2) ZEROFILL UNSIGNED NULL  AFTER `5_I_SALES_AMOUNT`;

CREATE SCHEMA GMC;
CREATE TABLE GMC_SKC_VITHU_BILL
(
	COMPANY                     VARCHAR(5),
	BOOK_NUMBER 				VARCHAR(10) ,
	BILL_NUMBER					INTEGER UNSIGNED,
	14_5_I_SALES_AMOUNT  		DOUBLE(10,2) UNSIGNED ZEROFILL,
	14_5_I_SALES_TAX	        DOUBLE(10,2) UNSIGNED ZEROFILL,
	5_I_SALES_AMOUNT       		DOUBLE(10,2) UNSIGNED ZEROFILL,
	5_I_SALES_TAX		        DOUBLE(10,2) UNSIGNED ZEROFILL,
	NTAS 						DOUBLE(10,2) UNSIGNED ZEROFILL,
	TOTAL						DOUBLE(20,2) UNSIGNED ZEROFILL,
	DATE_OF_SALES				DATE,
	CREATION_DATE		        DATE,
	LAST_MODIFIED_DATE			DATE,
	CONSTRAINT VITHU_BKNO_BLNO_PK PRIMARY KEY ( COMPANY, BOOK_NUMBER, BILL_NUMBER)
);